version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cafe-network

  # Menu Service
  menu-service:
    build:
      context: ./menu-services
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - cafe-network
    restart: on-failure

  # Order Service
  order-service:
    build:
      context: ./order-services
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - menu-service
      - inventory-service
      - customer-service
    networks:
      - cafe-network
    restart: on-failure

  # Payment Service
  payment-service:
    build:
      context: ./payment-services
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
      - order-service
    networks:
      - cafe-network
    restart: on-failure

  # Inventory Service
  inventory-service:
    build:
      context: ./inventory-services
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    networks:
      - cafe-network
    restart: on-failure

  # Customer Service
  customer-service:
    build:
      context: ./customer-services
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    networks:
      - cafe-network
    restart: on-failure

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - menu-service
      - order-service
      - payment-service
      - inventory-service
      - customer-service
    networks:
      - cafe-network
    restart: on-failure

networks:
  cafe-network:
    driver: bridge

volumes:
  mongodb_data:
